//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassAPic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Exchange_Words
    {
        public int Id { get; set; }
        public string word { get; set; }
        public int GameId { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
