//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassAPic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Turns = new HashSet<Turn>();
        }
    
        public int Id { get; set; }
        public int NumberOfParticipants { get; set; }
        public string GeneratedWord { get; set; }
    
        public virtual ICollection<Turn> Turns { get; set; }
        public virtual User Users { get; set; }
    }
}
