//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassAPic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Guesses = new HashSet<Guess>();
            this.Game_Comments = new HashSet<Game_Comments>();
            this.Game_Scoring = new HashSet<Game_Scoring>();
            this.Game_Exchange_Words = new HashSet<Game_Exchange_Words>();
        }
    
        public int Id { get; set; }
        public int NumberOfGuesses { get; set; }
        public string StartingWord { get; set; }
        public bool GameOverMan { get; set; }
        public string AnimatedResult { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public int TimerInSeconds { get; set; }
        public int Exchanges { get; set; }
        public string Mode { get; set; }
    
        public virtual ICollection<Guess> Guesses { get; set; }
        public virtual User Creator { get; set; }
        public virtual ICollection<Game_Comments> Game_Comments { get; set; }
        public virtual ICollection<Game_Scoring> Game_Scoring { get; set; }
        public virtual ICollection<Game_Exchange_Words> Game_Exchange_Words { get; set; }
    }
}
