//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassAPic.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PassAPicModelContainer : DbContext
    {
        public PassAPicModelContainer()
            : base("name=PassAPicModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Guess> Guesses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<PushRegister> PushRegisters { get; set; }
        public virtual DbSet<EasyWord> EasyWords { get; set; }
        public virtual DbSet<Game_Comments> Game_Comments { get; set; }
        public virtual DbSet<Game_Scoring> Game_Scoring { get; set; }
        public virtual DbSet<Leaderboard> Leaderboards { get; set; }
        public virtual DbSet<Game_Exchange_Words> Game_Exchange_Words { get; set; }
    }
}
