//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassAPic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushRegister
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
