//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassAPic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Games = new HashSet<Game>();
            this.CompletedGuesses = new HashSet<Guess>();
            this.NextGuesses = new HashSet<Guess>();
            this.PushRegisters = new HashSet<PushRegister>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public bool IsOnline { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Guess> CompletedGuesses { get; set; }
        public virtual ICollection<Guess> NextGuesses { get; set; }
        public virtual ICollection<PushRegister> PushRegisters { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
