//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassAPic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Games = new HashSet<Game>();
        }
    
        public int Id { get; set; }
        public System.Guid DeviceGuid { get; set; }
        public string Username { get; set; }
        public bool IsOnline { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual Guess Guess { get; set; }
    }
}
